version: '3.8'

services:
  vendor-db:
    image: mongo:7
    volumes:
      - vendor-db:/data/db

  product-db:
    image: mongo:7
    volumes:
      - product-db:/data/db

  vendor-svc:
    build: ./vendor-svc
    ports: ["3001:3001"]
    environment:
      PORT: 3001
      MONGO_URI: mongodb://vendor-db:27017/vendors
    depends_on: [vendor-db]

  product-svc:
    build: ./product-svc
    ports: ["3002:3002"]
    environment:
      PORT: 3002
      MONGO_URI: mongodb://product-db:27017/products
      VENDOR_SERVICE_URL: http://vendor-svc:3001
    depends_on: [product-db, vendor-svc]

volumes:
  vendor-db:
  product-db:
